base: &base
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  pool: 5
  username: root
  password:
  host: 127.0.0.1

development:
  <<: *base
  database: vehicle_position_development

test:
  <<: *base
  database: vehicle_position_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  <<: *base
  database: vehicle_position
